# Generated by Django 5.1.7 on 2025-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Введите номер стола",
                        max_length=50,
                        verbose_name="номер стола",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите содержимое", verbose_name="содержимое"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузити фотографию",
                        null=True,
                        upload_to="table_image/",
                        verbose_name="фото",
                    ),
                ),
                (
                    "table_occupiers",
                    models.DateTimeField(default=240, verbose_name="занятость стола"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="дата последнего изменения",
                    ),
                ),
                (
                    "reservation",
                    models.BooleanField(default=False, verbose_name="Бронь"),
                ),
            ],
            options={
                "verbose_name": "стол",
                "verbose_name_plural": "столы",
                "ordering": ["number"],
            },
        ),
    ]
