# Generated by Django 5.1.7 on 2025-03-28 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField(help_text="Введите номер стола", verbose_name="номер стола")),
                (
                    "sitting",
                    models.PositiveIntegerField(help_text="Введите сколько мест у стола", verbose_name="мест у стола"),
                ),
                ("content", models.TextField(help_text="Введите содержимое", verbose_name="содержимое")),
                (
                    "price",
                    models.CharField(default=3000, help_text="Введите цену", max_length=100, verbose_name="Цена"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузити фотографию",
                        null=True,
                        upload_to="table_image/photo",
                        verbose_name="фото",
                    ),
                ),
                ("table_occupiers", models.BooleanField(default=False, verbose_name="занятость стола")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="дата последнего изменения"),
                ),
            ],
            options={
                "verbose_name": "стол",
                "verbose_name_plural": "столы",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="TimeSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель заказа",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="restaurant.table"
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restaurant.timesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы ",
            },
        ),
    ]
