# Generated by Django 5.1.7 on 2025-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_name", models.CharField(help_text="Введите Ф.И.О", max_length=250, verbose_name="Ф.И.О.")),
                (
                    "email",
                    models.EmailField(help_text="Введите Email", max_length=250, unique=True, verbose_name="Email "),
                ),
                (
                    "comment",
                    models.TextField(help_text="Введите комментарий", max_length=250, verbose_name="комментарий"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.RemoveField(
            model_name="table",
            name="reservation",
        ),
        migrations.AddField(
            model_name="table",
            name="price",
            field=models.CharField(default=3000, help_text="Введите цену", max_length=100, verbose_name="Цена"),
        ),
    ]
